[package]
name = "draw_consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgr_9_comments ={ path = "../lgr_9_comments", default-features = false, features = ["shapes"]}
